### ISSUE TITLE
TS types missing from npm package

### ISSUE THREAD

**Issue by pocesar** [vardius/react-user-media#3]
npm package have no typings, maybe rollup isn't generating one because there's no declaration: true in tsconfig.json?

![image](https://user-images.githubusercontent.com/461084/64913628-1e5c5580-d71a-11e9-8b38-a4df6e8c727a.png)

**Comment by vardius** [comment]
I suppose this might be the reason 
https://github.com/vardius/react-user-media/blob/c5acaae23a804887fdbde8de5ed8cc9cad7e5727/rollup.config.js#L20

**Comment by vardius** [comment]
Thanks @pocesar for the info, if you could kindly let me know if version xhttps://github.com/vardius/react-user-media/releases/tag/v1.0.1 fixes the issue
